Cross platform support
zestymarket/haven pull request #1
Opened 2022-02-21 11:16 UTC by NSTCG

* Added Virtual Joystick for mobile 
* Changed framework , to support AR
* 1 tap locomotion for cardboard and AR ( press and hold 1sec)
* Incremental speed on pc ( when pressing shift)
* Disabled controller mesh and related meshes on AR ,cardboard mobile and PC sessioans
* Restricted player vertical movement
* World's boundary is set to restric player movement outside it 
* Added inVR teleportation
* Added Full screen button
* 360 view  toggle for device orientation feature

2022-02-21 15:20 UTC, msub2 commented
Functionality looks good, but just from a code-formatting perspective I would appreciate it if you could:
- Clean up any lines that are just commented out and not going to be used for anything.
- Reduce the amount of white space, I see a lot of instances where there's 4 lines of whitespace for no real reason
- Make sure indentation is consistent, I see a lot of misaligned lines
- Make spacing consistent, (space after if/else, before curly braces, on each side of an equation operator, etc)

Let me know if you need more specific examples

2022-02-21 16:20 UTC, NSTCG commented
Thanks for the feedback!
Formatted the code.

2022-02-21 17:17 UTC, Srile commented
Looks good so far. Thank you for your work. I have some comments:

1. Please put each component in its own `.js` file, as that significantly improves readability, I would even suggest moving components dedicated to locomotion into a subfolder of /js/ named `locomotion`.

2. Are all the images comitted required to be in the project?

Thank you, I think after those are resolved, I can get on with merging.

2022-02-21 17:41 UTC, msub2 requested changes
Please see my comments, I should've caught it the first time I looked at it but there are fields here that shouldn't be changed for this to work properly on the website

2022-02-21 17:41 UTC, msub2 commented on js/auto-join-peer.js
> -      const hostId = `host-${this.username}-${this.roomName}`;
Do not change this, this is required for the app to work.

2022-02-21 17:41 UTC, msub2 commented on js/auto-join-peer.js
> +      // this.peer.on("error", this._onHostError.bind(this));
Why is this commented out?

2022-02-21 17:41 UTC, msub2 commented on js/auto-join-peer.js
> -      this.serverId = id;
Do not change this, this is required for the app to work.

2022-02-21 17:41 UTC, msub2 commented on js/auto-join-peer.js
> -        this.connectionId = id;
Do not change this, this is required for the app to work.

2022-02-21 17:41 UTC, msub2 commented on js/auto-join-peer.js
> +      this.isLocalhost = false;
Why did you change this? You can circumvent this check locally by navigating to 127.0.0.1 instead of localhost

2022-02-21 17:42 UTC, Srile commented on js/auto-join-peer.js
> +      this.isLocalhost = false;
There is stuff from local testing in there that I will be removing once the rest of the changes are in.

2022-02-21 17:43 UTC, Srile commented on js/auto-join-peer.js
> -        this.connectionId = id;
This will also not be merged in.

2022-02-21 17:43 UTC, Srile commented on js/auto-join-peer.js
> -      this.serverId = id;
Will not be merged in.

2022-02-21 17:43 UTC, Srile commented on js/auto-join-peer.js
> +      // this.peer.on("error", this._onHostError.bind(this));
This causes an automatic join function on failed hosting, don't think we need this?

2022-02-21 17:44 UTC, Srile commented on js/auto-join-peer.js
> +      // this.peer.on("error", this._onHostError.bind(this));
I removed that in `networking-testing`

2022-02-21 17:44 UTC, Srile commented on js/auto-join-peer.js
> -      const hostId = `host-${this.username}-${this.roomName}`;
Yes, this will not be merged in

2022-02-21 18:50 UTC, NSTCG commented
> Looks good so far. Thank you for your work. I have some comments:
> 
> 1. Please put each component in its own `.js` file, as that significantly improves readability, I would even suggest moving components dedicated to locomotion into a subfolder of /js/ named `locomotion`.
> 2. Are all the images comitted required to be in the project?
> 
> Thank you, I think after those are resolved, I can get on with merging.

Thanks @Srile  for the comments 
Put each component in its own .js file
made a dedicated folder for locomotion and added it project js path

as of commited images , just put that for reference for future , if we wanna switch color / design of controllers

2022-02-23 00:04 UTC, limbofeather commented
@Srile @msub2 Are we good to merge or are there more changes that need to addressed?

2022-02-23 00:42 UTC, msub2 commented
@Srile still needs to push some changes I went over with him earlier

2022-02-23 00:44 UTC, limbofeather commented
Ah ok, thanks for heads-up.

2022-02-24 06:47 UTC, Srile commented
Just tested it locally, the joysticks don't seem to work properly. I can only rotate around the Y axis with the left thumbstick and nothing else. 

Ideally, I would move with the left joystick and have full y and x axis view with the right one. Can you fix that? @NSTCG

2022-02-24 13:05 UTC, merged